import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/provider";
import Header from "@/components/shared/header";
import { languages } from "@/i18n/settings";
import { ChildrenProps } from "@/types";
import { dir } from "i18next";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

interface Props extends ChildrenProps {
  params: { lng: string };
}

export default async function RootLayout({ children, params }: Props) {
  const { lng } = await params;

  return (
    <html lang={lng} dir={dir(lng)} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative flex min-h-screen flex-col antialiased`}
      >
        <Provider>
          <Header />
          <main className="mx-auto mb-16 w-full max-w-5xl flex-1 px-4 py-24 sm:px-8">
            {children}
          </main>
          <Image
            src="/gradient-background-top.webp"
            alt="Description of image"
            className="absolute top-0 left-1/2 -z-10 w-full -translate-x-1/2"
            role="presentation"
            width={1512}
            height={550}
            priority
          />
        </Provider>
      </body>
    </html>
  );
}
